services:
  - type: web
    name: cybercoach-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import app; app.create_app()"
    startCommand: gunicorn -w 4 -b 0.0.0.0:8080 app:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GUNICORN_CMD_ARGS
        value: "--log-level info"
    healthCheckPath: /health
    healthCheckTimeout: 30
    healthCheckInterval: 10
    healthCheckRetries: 3
    minMemory: 512
    minCpu: 1
